language: bash

before_install:
  - sudo apt-get update && sudo apt-get install -y shellcheck

script:
  - ls -l
  - bash test.sh
  - ls -l  
  - cat file 

notifications:
   email:
      on_success: never
